#define WHERE                            1
#define NOT                              2
#define PLUS                             3
#define MINUS                            4
#define EQUAL                            5
#define LESS                             6
#define THAN                             7
#define TIME                             8
#define IS                               9
#define TIMES                           10
#define DIVIDE                          11
#define POWER                           12
#define IT                              13
#define LSPAR                           14
#define WRITE                           15
#define SEMICOLON                       16
#define TRACE                           17
#define IDENTIFIER                      18
#define RSPAR                           19
#define ASSIGN                          20
#define OF                              21
#define FOR                             22
#define IN                              23
#define FORRANGE                        24
#define DO                              25
#define ENDDO                           26
#define IF                              27
#define THEN                            28
#define ENDIF                           29
#define ELSE                            30
#define ELSEIF                          31
#define NUMTOKEN                        32
#define TIMETOKEN                       33
#define STRTOKEN                        34
#define TRUE                            35
#define FALSE                           36
#define CURRENTTIME                     37
#define NOW                             38
#define NULL1                           39
#define AMPERSAND                       40
#define NUMBER                          41
#define STRING                          42
#define LIST                            43
#define LPAR                            44
#define RPAR                            45
#define COMMA                           46
#define COUNT                           47
#define FIRST                           48
#define OR                              49
#define GREATER                         50
#define WITHIN                          51
#define TO                              52
#define OCCURS                          53
#define BEFORE                          54
#define OCCURRED                        55
#define AFTER                           56
