#define PLUS                             1
#define MINUS                            2
#define TIMES                            3
#define DIVIDE                           4
#define POWER                            5
#define WRITE                            6
#define SEMICOLON                        7
#define TRACE                            8
#define IDENTIFIER                       9
#define ASSIGN                          10
#define LPAR                            11
#define RPAR                            12
#define NUMTOKEN                        13
#define STRTOKEN                        14
#define AMPERSAND                       15
