#define PLUS                             1
#define MINUS                            2
#define TIMES                            3
#define DIVIDE                           4
#define POWER                            5
#define NOT                              6
#define IS                               7
#define WRITE                            8
#define SEMICOLON                        9
#define TRACE                           10
#define IDENTIFIER                      11
#define ASSIGN                          12
#define TIME                            13
#define LPAR                            14
#define RPAR                            15
#define NUMTOKEN                        16
#define STRTOKEN                        17
#define TIMETOKEN                       18
#define TRUE                            19
#define FALSE                           20
#define NULL1                           21
#define AMPERSAND                       22
#define NUMBER                          23
#define STRING                          24
#define LIST                            25
#define LSPAR                           26
#define RSPAR                           27
#define COMMA                           28
#define COUNT                           29
#define FIRST                           30
